# Generated by Django 4.0.4 on 2022-05-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='goolge_plus_link',
            new_name='google_plus_link',
        ),
    ]
